"""
quasi_symbolic.py
-----------------
Provides quasi-symbolic abstractions for syllogistic arguments.

Two methods, matching the three proposal techniques:

  PRIMARY — Technique 3: QuaSAR (Ranaldi, Valentino & Freitas, 2025):
    Uses Llama-generated 4-step QuaSAR outputs.  The s2 (Formalisation)
    section — a quasi-symbolic representation with predicates, variables,
    and constants mapped to abstract symbols — is extracted from a pre-
    computed cache file (generated by quasar_generator.py).

  FALLBACK — Technique 1: Neuro-Symbolic Integration:
    Rule-based NLP extraction using spaCy.  Content terms (nouns) are
    identified and replaced with X, Y, Z in order of first appearance.
    Used when the QuaSAR cache is unavailable for a given example.

Both methods produce an abstract text that is concatenated with the
original syllogism:
    "<abstract_form> </s> <original_syllogism>"

This provides XLM-RoBERTa with both the logical *structure* (content-free
symbols) and the original *content*, encouraging the model to attend to
logical form over plausibility.
"""

import re
import logging
from typing import List, Optional, Tuple, Dict, Set
from collections import OrderedDict

logger = logging.getLogger(__name__)

# ─── Abstract symbols (proposal uses X, Y in its example) ────────────────────
SYMBOLS = ["X", "Y", "Z"]

# ─── Conclusion detection patterns ───────────────────────────────────────────
CONCLUSION_PATTERNS = [
    r"[Tt]herefore[,.]?\s+",
    r"[Cc]onsequently[,.]?\s+",
    r"[Tt]hus[,.]?\s+",
    r"[Hh]ence[,.]?\s+",
    r"[Ss]o[,.]?\s+",
    r"[Aa]s a result[,.]?\s+",
    r"[Ii]t follows that\s+",
    r"[Ii]t can be deduced\s+(?:that\s+)?",
    r"[Ii]t is clear that\s+",
    r"[Ww]e can conclude\s+(?:that\s+)?",
    r"[Oo]ne can conclude\s+(?:that\s+)?",
    r"[Tt]he only logical conclusion is\s+(?:that\s+)?",
    r"[Tt]his has led to the conclusion that\s+",
    r"[Tt]his means that\s+",
    r"[Ii]n conclusion[,.]?\s+",
    r"[Aa]ccordingly[,.]?\s+",
    r"[Tt]his implies that\s+",
]
CONCLUSION_RE = re.compile("|".join(CONCLUSION_PATTERNS))


def split_syllogism(text: str) -> Tuple[List[str], str]:
    """
    Split a syllogism into (premises_list, conclusion_text).

    Strategy:
    1. Find the conclusion marker and split.
    2. Split the remaining text into individual premise sentences.

    Returns (premises, conclusion) or ([], text) on failure.
    """
    match = CONCLUSION_RE.search(text)
    if not match:
        # Fallback: treat last sentence as conclusion
        sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if s.strip()]
        if len(sentences) >= 2:
            return sentences[:-1], sentences[-1]
        return [], text

    premise_block = text[: match.start()].strip()
    conclusion = text[match.end():].strip().rstrip(".")

    premises = [
        s.strip()
        for s in re.split(r"(?<=[.!?])\s+", premise_block)
        if s.strip() and len(s.strip()) > 5
    ]

    return premises, conclusion


def extract_content_terms(nlp, sentences: List[str]) -> OrderedDict:
    """
    Extract the distinct content terms from a list of sentences using spaCy.

    Returns an OrderedDict mapping lemmatised term → set of surface forms,
    ordered by first appearance in the text.

    A "content term" is a head noun (NOUN/PROPN) from a noun chunk,
    excluding stopwords and very short words. We also include standalone
    NOUN/PROPN tokens that aren't part of noun chunks.
    """
    term_surfaces: OrderedDict = OrderedDict()  # lemma → set of surface forms

    for sent in sentences:
        doc = nlp(sent)

        # First pass: noun chunks (captures head nouns of noun phrases)
        chunk_root_indices = set()
        for chunk in doc.noun_chunks:
            head = chunk.root
            if head.pos_ in ("NOUN", "PROPN") and not head.is_stop and len(head.lemma_) > 2:
                lemma = head.lemma_.lower()
                if lemma not in term_surfaces:
                    term_surfaces[lemma] = set()
                # Store both the head token text and the full chunk text
                term_surfaces[lemma].add(head.text)
                term_surfaces[lemma].add(chunk.text)
                chunk_root_indices.add(head.i)

        # Second pass: standalone nouns not captured by noun chunks
        for token in doc:
            if (
                token.pos_ in ("NOUN", "PROPN")
                and not token.is_stop
                and len(token.lemma_) > 2
                and token.i not in chunk_root_indices
            ):
                lemma = token.lemma_.lower()
                if lemma not in term_surfaces:
                    term_surfaces[lemma] = set()
                term_surfaces[lemma].add(token.text)

    return term_surfaces


def replace_terms_with_symbols(
    text: str,
    term_to_symbol: Dict[str, str],
    nlp,
) -> str:
    """
    Replace all surface forms of each content term with its assigned symbol.

    Uses spaCy to find surface forms (matching by lemma), then regex-replaces
    longest forms first to avoid partial replacements.
    """
    doc = nlp(text)
    all_replacements: List[Tuple[str, str]] = []  # (surface_form, symbol)

    for token in doc:
        lemma = token.lemma_.lower()
        if lemma in term_to_symbol:
            all_replacements.append((token.text, term_to_symbol[lemma]))

    for chunk in doc.noun_chunks:
        root_lemma = chunk.root.lemma_.lower()
        if root_lemma in term_to_symbol:
            all_replacements.append((chunk.text, term_to_symbol[root_lemma]))

    # Deduplicate and sort by length (longest first for safe replacement)
    seen: Set[str] = set()
    unique_replacements = []
    for surface, symbol in sorted(all_replacements, key=lambda x: -len(x[0])):
        if surface not in seen:
            unique_replacements.append((surface, symbol))
            seen.add(surface)

    result = text
    for surface, symbol in unique_replacements:
        pattern = re.compile(re.escape(surface), re.IGNORECASE)
        result = pattern.sub(symbol, result)

    return result


# ─── Main Abstractor Class ────────────────────────────────────────────────────

class QuasiSymbolicAbstractor:
    """
    Transforms a natural-language syllogism into a quasi-symbolic abstract form.

    PRIMARY (QuaSAR / technique 3):
      Uses pre-computed Llama-generated QuaSAR cache.  The s2 (Formalisation)
      section is loaded from a JSON file keyed by syllogism ID.

    FALLBACK (Neuro-Symbolic / technique 1):
      spaCy-based rule extraction: identify content terms → replace with X/Y/Z.

    Example (QuaSAR s2):
      Input:  "All cars are vehicles. No animal is a car.
               Therefore, no animal is a vehicle."
      Output: "Let X = cars, Y = vehicles, Z = animals.
               Premise 1: All X are Y. Premise 2: No Z is X.
               Conclusion: No Z is Y."

    Example (spaCy fallback):
      Input:  same as above
      Output: "All X are Y. No Z is X. Therefore, no Z is Y."

    The abstract form is concatenated with the original text:
      "<abstract_form> </s> <original_syllogism>"
    """

    def __init__(self, spacy_model: str = "en_core_web_sm", quasar_cache: dict = None):
        """
        Parameters
        ----------
        spacy_model : str
            spaCy model for fallback extraction.
        quasar_cache : dict or None
            Pre-loaded QuaSAR cache: {id: {"quasar_s2": str, ...}}.
            If provided, QuaSAR s2 is used as primary abstraction source.
        """
        self._quasar_cache = quasar_cache or {}
        self._quasar_hits = 0
        self._fallback_hits = 0

        try:
            import spacy
            self.nlp = spacy.load(spacy_model)
            self._available = True
            logger.info(f"QuasiSymbolicAbstractor: spaCy model '{spacy_model}' loaded.")
        except ImportError:
            logger.warning("spaCy not installed. Quasi-symbolic abstraction disabled.")
            self._available = False
        except OSError:
            logger.warning(
                f"spaCy model '{spacy_model}' not found. "
                f"Run: python -m spacy download {spacy_model}"
            )
            self._available = False

        if self._quasar_cache:
            logger.info(f"QuaSAR cache loaded: {len(self._quasar_cache)} entries.")

    def set_quasar_cache(self, cache: dict):
        """Load or update the QuaSAR cache after initialization."""
        self._quasar_cache = cache
        logger.info(f"QuaSAR cache set: {len(cache)} entries.")

    def abstract(self, syllogism: str, item_id: str = None, quasar_mode: str = "s2") -> str:
        """
        Convert a syllogism to its abstract quasi-symbolic form.

        Parameters
        ----------
        quasar_mode : str
            "s2"    -- use only s2 (Formalisation)
            "s2_s3" -- use s2 + s3 (Formalisation + Explanation)
            "full"  -- use full 4-step QuaSAR output (s1+s2+s3+s4)

        Strategy:
        1. If item_id is provided and exists in QuaSAR cache -> use cache.
        2. Otherwise, fall back to spaCy-based extraction.
        3. If both fail, return the original text.
        """
        # PRIMARY: QuaSAR cache (technique 3)
        if item_id and item_id in self._quasar_cache:
            entry = self._quasar_cache[item_id]
            if quasar_mode == "full":
                full = entry.get("quasar_full", "")
                if full and len(full.strip()) > 10:
                    self._quasar_hits += 1
                    return full.strip()
            elif quasar_mode == "s2_s3":
                s2 = entry.get("quasar_s2", "")
                # Extract s3 from quasar_full
                full = entry.get("quasar_full", "")
                s3 = ""
                if full:
                    import re as re_mod
                    m = re_mod.search(r's3\s*\(Explanation\)\s*:?\s*(.*?)(?:s4\s*\(|$)', full, re_mod.DOTALL | re_mod.IGNORECASE)
                    if m:
                        s3 = m.group(1).strip()
                if s2 and len(s2.strip()) > 5:
                    combined = s2.strip()
                    if s3:
                        combined += " Explanation: " + s3
                    self._quasar_hits += 1
                    return combined
            else:  # s2 only (default)
                s2 = entry.get("quasar_s2", "")
                if s2 and len(s2.strip()) > 10:
                    self._quasar_hits += 1
                    return s2.strip()

        # FALLBACK: spaCy rule-based (technique 1)
        return self._abstract_spacy(syllogism)

    def _abstract_spacy(self, syllogism: str) -> str:
        """
        Fallback: spaCy-based quasi-symbolic abstraction (technique 1).
        Extracts content terms and replaces with X, Y, Z.
        """
        if not self._available:
            return syllogism

        try:
            premises, conclusion = split_syllogism(syllogism)
            if len(premises) < 1:
                self._fallback_hits += 1
                return syllogism

            # Collect all sentences for term extraction
            all_sentences = premises + [conclusion]

            # Extract content terms ordered by first appearance
            term_surfaces = extract_content_terms(self.nlp, all_sentences)
            unique_lemmas = list(term_surfaces.keys())

            # Need at least 2 distinct terms for meaningful abstraction
            if len(unique_lemmas) < 2:
                logger.debug("Fewer than 2 distinct terms found; returning original.")
                return syllogism

            # Assign symbols to the first 3 terms (standard syllogism has 3)
            term_to_symbol = {}
            for i, lemma in enumerate(unique_lemmas[:len(SYMBOLS)]):
                term_to_symbol[lemma] = SYMBOLS[i]

            # Build the abstract form by replacing terms with symbols
            abstract_parts = []
            for sent in all_sentences:
                abstracted = replace_terms_with_symbols(sent, term_to_symbol, self.nlp)
                abstract_parts.append(abstracted.strip())

            abstract_text = " ".join(abstract_parts)
            self._fallback_hits += 1
            return abstract_text

        except Exception as e:
            logger.debug(f"QuasiSymbolic abstraction failed: {e}")
            self._fallback_hits += 1
            return syllogism

    def abstract_batch(self, syllogisms: List[str], item_ids: List[str] = None) -> List[str]:
        """Process a list of syllogisms in batch."""
        if item_ids:
            return [self.abstract(s, iid) for s, iid in zip(syllogisms, item_ids)]
        return [self.abstract(s) for s in syllogisms]

    def get_stats(self) -> dict:
        """Return abstraction source statistics."""
        return {
            "quasar_hits": self._quasar_hits,
            "fallback_hits": self._fallback_hits,
            "quasar_cache_size": len(self._quasar_cache),
        }

    def demo(self, syllogism: str) -> None:
        """Pretty-print the abstraction steps for a syllogism."""
        print("=" * 70)
        print("ORIGINAL:")
        print(" ", syllogism)

        premises, conclusion = split_syllogism(syllogism)
        print("\nSPLIT:")
        for i, p in enumerate(premises, 1):
            print(f"  Premise {i}: {p}")
        print(f"  Conclusion: {conclusion}")

        if self._available:
            all_sentences = premises + [conclusion]
            term_surfaces = extract_content_terms(self.nlp, all_sentences)
            unique_lemmas = list(term_surfaces.keys())
            print(f"\nCONTENT TERMS (in order of appearance):")
            for i, lemma in enumerate(unique_lemmas[:len(SYMBOLS)]):
                surfaces = term_surfaces[lemma]
                print(f"  {SYMBOLS[i]} <- '{lemma}' (surfaces: {surfaces})")

        abstract = self.abstract(syllogism)
        print("\nABSTRACT FORM:")
        print(" ", abstract)
        print("=" * 70)


# ─── Quick test ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    abstractor = QuasiSymbolicAbstractor()
    examples = [
        "All cars are a type of vehicle. No animal is a car. Therefore, no animal can be a vehicle.",
        "Not all canines are aquatic creatures known as fish. It is certain that no fish belong to the class of mammals. Therefore, every canine falls under the category of mammals.",
        "Every single cat is an animal. Anything that can be called a dog is, without exception, an animal. Every dog is a cat.",
        "Everything that is a planet is a celestial body. Anything that is a sun is a celestial body. There exists at least one sun that is a planet.",
        "Nothing that is a soda is a juice. A portion of the things that are beverages are juices. The only logical conclusion is that some beverages are not sodas.",
    ]
    for ex in examples:
        abstractor.demo(ex)
        print()
