"""
config.py
---------
Configuration for Subtask 2: Syllogistic Reasoning with Relevant Premise
Retrieval.

Architecture:
  - JointSyllogismClassifier: XLM-RoBERTa encoder (shared with subtask1)
    with two heads:
      Head 1 (validity):  Linear(768 → 2)  cross-entropy loss
      Head 2 (premises):  Linear(768 → 1) per-premise  BCEWithLogitsLoss
  - Initialized from the pretrained subtask1 checkpoint (encoder + validity
    head), with the premise head randomly initialized.
  - Dataset generated from subtask1 training data by injecting distractor
    premises (Technique 1: Llama LLM; Technique 2: cross-contamination).

Training objective:
  Total loss = α * CE(validity) + β * BCE(per-premise relevance)
  We compute BCE only over actual premise positions (masked loss).
"""

import os

# ─── Paths ───────────────────────────────────────────────────────────────────
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# Input: subtask1 training data (source for distractor injection)
S1_TRAIN_DATA_PATH = os.path.join(
    BASE_DIR, "semeval_2026_task_11", "train_data", "subtask 1", "train_data.json"
)

# Test data: subtask2 (190 items, 5-8 premises each)
TEST_DATA_PATH = os.path.join(
    BASE_DIR, "semeval_2026_task_11", "test_data", "subtask 2", "test_data_subtask_2.json"
)

# Subtask2 outputs
OUTPUT_DIR = os.path.join(BASE_DIR, "src", "subtask2", "outputs")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Generated training dataset (from dataset_generator.py)
GENERATED_TRAIN_PATH = os.path.join(OUTPUT_DIR, "generated_train_data.json")

# Model checkpoint (fine-tuned JointSyllogismClassifier)
MODEL_SAVE_DIR = os.path.join(OUTPUT_DIR, "model_checkpoint")
os.makedirs(MODEL_SAVE_DIR, exist_ok=True)

# Subtask1 checkpoint to initialize from
S1_MODEL_SAVE_DIR = os.path.join(BASE_DIR, "src", "subtask1", "outputs", "model_checkpoint")
S1_STEERING_VECTORS_PATH = os.path.join(BASE_DIR, "src", "subtask1", "outputs", "steering_vectors.pt")
S1_QUASAR_TEST_CACHE = os.path.join(BASE_DIR, "src", "subtask1", "outputs", "quasar_test_cache.json")
S1_QUASAR_TRAIN_CACHE = os.path.join(BASE_DIR, "src", "subtask1", "outputs", "quasar_train_cache.json")

# Subtask2-specific QuaSAR cache (for subtask2 test items, generated by generate_quasar_subtask2.py)
S2_QUASAR_TEST_CACHE = os.path.join(OUTPUT_DIR, "quasar_s2_test_cache.json")

# Predictions output
PREDICTIONS_APPROACH1_PATH = os.path.join(OUTPUT_DIR, "predictions_approach1.json")
PREDICTIONS_APPROACH2_PATH = os.path.join(OUTPUT_DIR, "predictions_approach2.json")
EVAL_RESULTS_PATH = os.path.join(OUTPUT_DIR, "eval_results.json")

# ─── Dataset Generation ───────────────────────────────────────────────────────
# Number of distractor premises to inject per source item.
# Test set has avg 5.91 total premises (2 original + 3-4 distractors → 5-6 total).
# So we target 4-5 distractors → 6-7 total premises per item, matching test distribution.
MIN_DISTRACTORS = 4
MAX_DISTRACTORS = 5
# How many augmented samples to create per original training item
SAMPLES_PER_ITEM = 2   # → 960 × 2 = 1920 generated training examples

# ─── Model ───────────────────────────────────────────────────────────────────
# Shared with subtask1
MODEL_NAME = "xlm-roberta-base"
NUM_LABELS = 2              # 0=invalid, 1=valid
MAX_SEQ_LEN = 512           # longer for multi-premise syllogisms
MAX_PREMISES = 8            # maximum number of premises expected
DROPOUT_RATE = 0.3
HF_CACHE_DIR = os.environ.get("HF_HOME", None)

# ─── Training ─────────────────────────────────────────────────────────────────
BATCH_SIZE = 8
EVAL_BATCH_SIZE = 16
NUM_EPOCHS = 30
# Differential learning rates: encoder already fine-tuned on subtask1
ENCODER_LR = 1e-5           # lowered: reduce overfitting on generated data
HEAD_LR = 1e-4              # premise head is randomly initialized
WEIGHT_DECAY = 0.02         # stronger regularization
WARMUP_RATIO = 0.1
MAX_GRAD_NORM = 1.0
VALIDATION_SPLIT = 0.0      # 0 = use test data as validation (real distribution)
SEED = 42
USE_FP16 = True
GRADIENT_ACCUMULATION_STEPS = 1

# ─── Multi-task loss weights ─────────────────────────────────────────────────
VALIDITY_LOSS_WEIGHT = 0.5  # α
PREMISE_LOSS_WEIGHT  = 0.5  # β
# Positive premise weight in BCEWithLogitsLoss.
# With avg 6 premises per item, 2 relevant, 50% valid items:
#   overall positive fraction ≈ 50% × 2/6 ≈ 16.7%
#   pos_weight ≈ (1-0.167)/0.167 ≈ 5.0
PREMISE_POS_WEIGHT = 5.0

# ─── QuaSAR ──────────────────────────────────────────────────────────────────
USE_QUASI_SYMBOLIC = True
ABSTRACT_SEP = " </s> "
QUASAR_MODE = "full"
SPACY_MODEL = "en_core_web_sm"

# ─── Activation Steering (inherited from subtask1 vectors) ───────────────────
# We load and apply the subtask1 steering vectors (same encoder, same direction)
USE_ACTIVATION_STEERING = True
STEERING_LAYERS = [11]
STEERING_KNN = 10

# ─── Labels ──────────────────────────────────────────────────────────────────
LABEL2ID = {False: 0, True: 1}
ID2LABEL  = {0: False, 1: True}

# ─── LLM for dataset generation ──────────────────────────────────────────────
LLAMA_MODEL_NAME = "meta-llama/Llama-3.1-8B-Instruct"
USE_4BIT         = False     # fp16 across 3 GPUs (3x RTX 2080 Ti = 33GB, model ~16GB fp16)
LLM_MAX_NEW_TOKENS = 512

# ─── Llama QLoRA Fine-tuning (Approach 3: Decoder-based) ─────────────────────
LLAMA_LORA_R          = 16
LLAMA_LORA_ALPHA      = 32
LLAMA_LORA_DROPOUT    = 0.1
LLAMA_LORA_TARGETS    = ["q_proj", "k_proj", "v_proj", "o_proj",
                         "gate_proj", "up_proj", "down_proj"]
LLAMA_FT_EPOCHS       = 3
LLAMA_FT_BATCH_SIZE   = 1
LLAMA_FT_GRAD_ACCUM   = 16   # effective batch = 1 * 16 = 16
LLAMA_FT_LR           = 2e-4
LLAMA_FT_MAX_SEQ_LEN  = 768
LLAMA_FT_USE_4BIT     = True  # QLoRA: 4-bit base model + fp16 adapters
LLAMA_FT_SAVE_DIR     = os.path.join(OUTPUT_DIR, "llama_lora_checkpoint")
LLAMA_PREDICTIONS_PATH = os.path.join(OUTPUT_DIR, "predictions_llama.json")
