"""
config.py
---------
Central configuration for Subtask 1: Syllogistic Reasoning in English.

Approach (from proposal):
  - Base model: XLM-RoBERTa (multilingual, strong cross-lingual transfer)
  - Neuro-Symbolic Integration + Quasi-Symbolic Abstraction: extract the
    logical form of an argument (e.g., "All X are Y") and provide it to
    the model alongside the original text, so that the model pays more
    attention to structure than to wording.
    (Adapted from Ranaldi, Valentino & Freitas, 2025 — QuaSAR, arXiv:2502.12616)
  - Activation Steering (Valentino et al., 2025 — arXiv:2505.12189): post
    fine-tuning, compute contrastive activation vectors using behaviour-based
    D+/D- sets (correct vs incorrect predictions) to steer the model away
    from content-biased reasoning at inference time.
"""

import os

# ─── Paths ───────────────────────────────────────────────────────────────────
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

TRAIN_DATA_PATH = os.path.join(
    BASE_DIR,
    "semeval_2026_task_11", "train_data", "subtask 1", "train_data.json"
)
TEST_DATA_PATH = os.path.join(
    BASE_DIR,
    "semeval_2026_task_11", "test_data", "subtask 1", "test_data_subtask_1.json"
)
EVAL_KIT_REFERENCE = os.path.join(
    BASE_DIR,
    "semeval_2026_task_11", "evaluation_kit", "task 1 & 3", "mock_reference.json"
)
EVAL_SCRIPT_PATH = os.path.join(
    BASE_DIR,
    "semeval_2026_task_11", "evaluation_kit", "task 1 & 3", "evaluation_script.py"
)

OUTPUT_DIR = os.path.join(BASE_DIR, "src", "subtask1", "outputs")
MODEL_SAVE_DIR = os.path.join(OUTPUT_DIR, "model_checkpoint")
STEERING_VECTORS_PATH = os.path.join(OUTPUT_DIR, "steering_vectors.pt")
PREDICTIONS_PATH = os.path.join(OUTPUT_DIR, "predictions.json")
EVAL_RESULTS_PATH = os.path.join(OUTPUT_DIR, "eval_results.json")

# QuaSAR cache files (generated by Llama, used as input to XLM-RoBERTa)
QUASAR_TRAIN_CACHE = os.path.join(OUTPUT_DIR, "quasar_train_cache.json")
QUASAR_TEST_CACHE = os.path.join(OUTPUT_DIR, "quasar_test_cache.json")

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(MODEL_SAVE_DIR, exist_ok=True)

# ─── Model ───────────────────────────────────────────────────────────────────
# xlm-roberta-base: 12-layer, 768-hidden, 270M params — natively multilingual.
# Good for subtask 1 (English) and generalises to subtasks 3 & 4 (multilingual).
MODEL_NAME = "xlm-roberta-base"
NUM_LABELS = 2          # 0 = invalid, 1 = valid
MAX_SEQ_LEN = 384       # increased for QuaSAR formalisation + original text

# HuggingFace cache — override on cluster for fast SSD storage
HF_CACHE_DIR = os.environ.get("HF_HOME", None)

# ─── Training Hyper-parameters ────────────────────────────────────────────────
BATCH_SIZE = 8
EVAL_BATCH_SIZE = 32
NUM_EPOCHS = 15
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
WARMUP_RATIO = 0.1       # 10% of steps for linear warm-up
MAX_GRAD_NORM = 1.0
VALIDATION_SPLIT = 0.1   # 10% of train set held out for validation
EARLY_STOPPING_PATIENCE = 99  # effectively disabled — always run all epochs
SEED = 42
DROPOUT_RATE = 0.3

# ─── GPU / Training Optimisation ─────────────────────────────────────────
USE_FP16 = True                     # Mixed-precision (FP16) for speed
GRADIENT_ACCUMULATION_STEPS = 1     # Effective batch = BATCH_SIZE × accum × n_gpus
USE_GRADIENT_CHECKPOINTING = False  # Trade compute for memory (enable for Llama)

# ─── Quasi-Symbolic Abstraction (QuaSAR) ─────────────────────────────────────
# When True, prepend a quasi-symbolic form to every input:
#   "<QuaSAR s2 formalisation> </s> <original text>"
#
# Primary method (technique 3): Llama-generated QuaSAR 4-step output.
#   The s2 (Formalisation) section is extracted and used as the abstract form.
#   Requires quasar_*_cache.json files (generated by quasar_generator.py).
#
# Fallback method (technique 1): spaCy rule-based X/Y/Z replacement.
#   Used if QuaSAR cache is not available for a given example.
USE_QUASI_SYMBOLIC = True
ABSTRACT_SEP = " </s> "   # XLM-RoBERTa's native separator token

# QuaSAR input mode:
#   "s2"      — s2 (formalisation) only  (short, ~10 tokens)
#   "s2_s3"   — s2 + s3 (formalisation + explanation, ~50 tokens)
#   "full"    — full 4-step QuaSAR output (s1+s2+s3+s4, ~100 tokens)
# Using more of the chain-of-thought gives XLM-RoBERTa richer signal.
QUASAR_MODE = "full"

# spaCy model for fallback neuro-symbolic extraction
SPACY_MODEL = "en_core_web_sm"

# ─── Activation Steering (CAA/K-CAST) ────────────────────────────────────────
# Adapted from Valentino et al. (2025) for encoder-only XLM-RoBERTa.
# The original paper targets decoder-only models (Llama, Gemma, Qwen); we
# apply the same contrastive steering principle to [CLS] layer activations.
#
# D+ / D- are BEHAVIOUR-BASED (per the paper):
#   D+ = examples where model predicts correctly (structure-based reasoning)
#   D- = examples where model predicts incorrectly (content-biased errors)
#
# Layers to hook: last quarter of XLM-RoBERTa-base (layers 9-11 of 12).
# Valentino et al. (2025) found that layers in the last third-quarter are
# most informative for validity vs. plausibility and best for steering.
STEERING_LAYERS = [11]  # Layer 11 has strongest content signal (||delta||=1.07)
STEERING_ALPHA = 1.0          # default scaling factor for the steering vector
STEERING_KNN = 10             # k for K-CAST nearest-neighbour lookup
USE_ACTIVATION_STEERING = True

# ─── Label Mapping ───────────────────────────────────────────────────────────
LABEL2ID = {False: 0, True: 1}
ID2LABEL = {0: False, 1: True}

# ─── Llama Model (alternative/supplementary classifier) ──────────────────
# Llama can be used (a) as an alternative classifier with LoRA fine-tuning,
# or (b) to generate quasi-symbolic abstractions (original QuaSAR approach).
# MUST use Instruct variant — base model doesn't follow structured prompts.
LLAMA_MODEL_NAME = "meta-llama/Llama-3.1-8B-Instruct"
USE_LORA = True           # LoRA for parameter-efficient fine-tuning
LORA_R = 16               # LoRA rank
LORA_ALPHA = 32           # LoRA scaling factor
LORA_DROPOUT = 0.1        # LoRA dropout
USE_4BIT = True           # QLoRA: 4-bit quantisation for memory efficiency
