"""
config.py
---------
Central configuration for Subtask 3: Syllogistic Reasoning — Multilingual.

Same approach as Subtask 1 but on translated syllogisms (11 languages).
The model input uses the translated text (syllogism_t), while QuaSAR
generation uses the English original (syllogism) since Llama works best
in English. XLM-RoBERTa handles multilingual input natively.
"""

import os

# ─── Paths ───────────────────────────────────────────────────────────────────
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

TRAIN_DATA_PATH = os.path.join(
    BASE_DIR,
    "semeval_2026_task_11", "train_data", "subtask 3", "train_data_translated.json"
)
TEST_DATA_PATH = os.path.join(
    BASE_DIR,
    "semeval_2026_task_11", "test_data", "subtask 3", "test_data_subtask_3.json"
)
EVAL_KIT_REFERENCE = os.path.join(
    BASE_DIR,
    "semeval_2026_task_11", "evaluation_kit", "task 1 & 3", "mock_reference.json"
)
EVAL_SCRIPT_PATH = os.path.join(
    BASE_DIR,
    "semeval_2026_task_11", "evaluation_kit", "task 1 & 3", "evaluation_script.py"
)

OUTPUT_DIR = os.path.join(BASE_DIR, "src", "subtask3", "outputs")
MODEL_SAVE_DIR = os.path.join(OUTPUT_DIR, "model_checkpoint")
STEERING_VECTORS_PATH = os.path.join(OUTPUT_DIR, "steering_vectors.pt")
PREDICTIONS_PATH = os.path.join(OUTPUT_DIR, "predictions.json")
EVAL_RESULTS_PATH = os.path.join(OUTPUT_DIR, "eval_results.json")

# QuaSAR cache files (generated by Llama on English syllogisms)
QUASAR_TRAIN_CACHE = os.path.join(OUTPUT_DIR, "quasar_train_cache.json")
QUASAR_TEST_CACHE = os.path.join(OUTPUT_DIR, "quasar_test_cache.json")

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(MODEL_SAVE_DIR, exist_ok=True)

# ─── Model ───────────────────────────────────────────────────────────────────
MODEL_NAME = "xlm-roberta-base"
NUM_LABELS = 2          # 0 = invalid, 1 = valid
MAX_SEQ_LEN = 384       # increased for QuaSAR formalisation + original text

# HuggingFace cache
HF_CACHE_DIR = os.environ.get("HF_HOME", None)

# ─── Training Hyper-parameters (same as subtask1 best config) ─────────────────
BATCH_SIZE = 32
EVAL_BATCH_SIZE = 32
NUM_EPOCHS = 15
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
WARMUP_RATIO = 0.1
MAX_GRAD_NORM = 1.0
VALIDATION_SPLIT = 0.25
EARLY_STOPPING_PATIENCE = 99
SEED = 42
DROPOUT_RATE = 0.3

# ─── GPU / Training Optimisation ─────────────────────────────────────────
USE_FP16 = True
GRADIENT_ACCUMULATION_STEPS = 1
USE_GRADIENT_CHECKPOINTING = False

# ─── Quasi-Symbolic Abstraction (QuaSAR) ─────────────────────────────────────
USE_QUASI_SYMBOLIC = True
ABSTRACT_SEP = " </s> "

# QuaSAR input mode: "s2", "s2_s3", or "full"
QUASAR_MODE = "full"

# spaCy model for fallback
SPACY_MODEL = "en_core_web_sm"

# ─── Activation Steering (CAA) ────────────────────────────────────────────
STEERING_LAYERS = [11]
STEERING_ALPHA = 1.0
STEERING_KNN = 10
USE_ACTIVATION_STEERING = True

# ─── Label Mapping ───────────────────────────────────────────────────────────
LABEL2ID = {False: 0, True: 1}
ID2LABEL = {0: False, 1: True}

# ─── Llama Model (for QuaSAR generation) ──────────────────────────────────
LLAMA_MODEL_NAME = "meta-llama/Llama-3.1-8B-Instruct"
USE_LORA = True
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.1
USE_4BIT = True
